#!/usr/bin/env php
<?php

define('LARAVEL_START', microtime(true));

/*
|--------------------------------------------------------------------------
| Check If The Application Is Under Maintenance
|--------------------------------------------------------------------------
|
| If the application is in maintenance mode, we will load this file so that
| we can instantly return a pre-rendered response. We want to do this
| immediately as to not load the rest of the framework for a call.
|
*/

if (file_exists(__DIR__.'/vendor/laravel/framework/src/Illuminate/Foundation/Console/Kernel.php')) {
    require __DIR__.'/vendor/autoload.php';

    $app = require_once __DIR__.'/bootstrap/app.php';

    $kernel = $app->make(Illuminate\Contracts\Console\Kernel::class);

    $status = $kernel->handle(
        $input = new Symfony\Component\Console\Input\ArgvInput,
        new Symfony\Component\Console\Output\ConsoleOutput
    );

    $kernel->terminate($input, $status);

    exit($status);
}

// Fallback for when composer is not run yet
require __DIR__.'/bootstrap/app.php';

$app->make(Illuminate\Contracts\Console\Kernel::class)
    ->bootstrap()
    ->handle(
        $input = new Symfony\Component\Console\Input\ArgvInput,
        new Symfony\Component\Console\Output\ConsoleOutput
    )
    ->terminate();